services:
  postgresql:
    image: bitnami/postgresql:latest
    volumes:
      - db:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=baddie
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=c2
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  db:
    driver: local
